site_name: helmfile2compose
site_url: https://helmfile2compose.github.io/
site_description: Convert Kubernetes manifests to compose.yml + Caddyfile
repo_url: https://github.com/helmfile2compose/h2c-core
repo_name: helmfile2compose/h2c-core


theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  custom_dir: overrides
  features:
    - navigation.sections
    - content.code.copy
    - search.suggest

nav:
  - Home: index.md
  - User guide:
      - Operations: user/operations.md
      - Advanced: user/advanced.md
  - Maintainer guide:
      - Your project: maintainer/your-project.md
      - Configuration: maintainer/configuration.md
      - Known workarounds:
          - Overview: maintainer/known-workarounds/index.md
          - Common charts: maintainer/known-workarounds/common-charts.md
          - kube-prometheus-stack: maintainer/known-workarounds/kube-prometheus-stack.md
      - h2c-manager: maintainer/h2c-manager.md
  - Developer guide:
      - Concepts: developer/concepts.md
      - Architecture: developer/architecture.md
      - Core architecture: developer/core-architecture.md
      - Code quality: developer/code-quality.md
      - Testing: developer/testing.md
      - Writing extensions:
          - Overview: developer/extensions/index.md
          - Converters: developer/extensions/writing-converters.md
          - CRD patterns: developer/extensions/writing-crd-patterns.md
          - Transforms: developer/extensions/writing-transforms.md
          - Rewriters: developer/extensions/writing-rewriters.md
  - Extension catalogue: catalogue.md
  - Troubleshooting: troubleshooting.md
  - Reference:
      - Limitations: limitations.md
      - Roadmap: roadmap.md
  - About: about.md

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

copyright: Made with despair and dark rituals (and <a href="https://squidfunk.github.io/mkdocs-material/">MkDocs Material</a>)
